### ISSUE TITLE
Change color via Code doesn't Work.

### ISSUE THREAD

**Issue by ilovepwa** [armespavong/ionic-plugin-navigation-bar-color#1]
Ich define the base color in the XML. This works fine. But when i import your module inside my app i get errors.

**Comment by patiparnne** [comment]
Hi. Sorry I just saw this.
What kind of error did you get?
Can you describe me exactly?

**Comment by ilovepwa** [comment]
index.js:75 Uncaught TypeError: Object(...) is not a function
    at index.js:75
    at Module../node_modules/ionic-plugin-navigation-bar-color/index.js (index.js:113)
    at __webpack_require__ (bootstrap:83)
    at Module../src/app/app.module.ts (app.component.ts:11)
    at __webpack_require__ (bootstrap:83)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:83)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:83)
    at checkDeferredModules (bootstrap:45)

**Comment by jpolo-bda** [comment]
Hi everybody.
The same happens to me. 
It works from XML, but not from ionic code. And the errors are exactly the same.
Regards.

**Comment by patiparnne** [comment]
Hi. 
Have you guys tried adding the code inside platform.ready()?

Example:
```
this.platform.ready().then(() => {
    this.navigationBarColor.backgroundColorByHexString('#000000');
})
```

I'm not sure which version of Ionic you are using.
I,m using this plugin in my Ionic 3 projects and it works fine.

I found some people faced issues for ionic plugins in Ionic 4
https://forum.ionicframework.com/t/ionic-4-native-plugin-problem/136670/2

*Anyway, I've did some changes. Please try installing version 1.0.2

**Comment by GoTo225** [comment]
@armespavong I'm also facing this issue. I'm pretty sure it's related to ionic-native 5. It looks like they've did some major changes in v5.0 like upgrading to rxjs 6.

**Comment by pslyman** [comment]
> @armespavong I'm also facing this issue. I'm pretty sure it's related to ionic-native 5. It looks like they've did some major changes in v5.0 like upgrading to rxjs 6.

From what I've seen that's very likely the issue. Doesn't work for me either. As soon as it hits the import and provider, the error appears. Have you found a way around it?

**Comment by anthonyjuarezsolis** [comment]
Doesn't work on Ionic 4/5 : 
`vendor.js: 177023 Uncaught TypeError: Object (...) is not a function
    at vendor.js: 177023
    at Module ../ node_modules / ionic-plugin-navigation-bar-color / index.js (vendor.js: 177061)
    at __webpack_require__ (runtime.js: 85)
    at Module ../ src / app / app.module.ts (main.js: 995)
    at __webpack_require__ (runtime.js: 85)
    at Module ../ src / main.ts (main.js: 1382)
    at __webpack_require__ (runtime.js: 85)
    at Object.0 (main.js: 1407)
    at __webpack_require__ (runtime.js: 85)
    at checkDeferredModules (runtime.js: 46)
(anonymous) @ vendor.js: 177023
./node_modules/ionic-plugin-navigation-bar-color/index.js @ vendor.js: 177061
__webpack_require__ @ runtime.js: 85
./src/app/app.module.ts @ main.js: 995
__webpack_require__ @ runtime.js: 85
./src/main.ts @ main.js: 1382
__webpack_require__ @ runtime.js: 85
0 @ main.js: 1407
__webpack_require__ @ runtime.js: 85
checkDeferredModules @ runtime.js: 46
webpackJsonpCallback @ runtime.js: 33
(anonymous) @ main.js: 1
localhost /: 1 Unchecked runtime.lastError: The message port closed before a response was received.`

**Comment by somq** [comment]
I confirm, this is probably due to the new wraping (/ngx) in Ionic 4/5.
Would you eventually make a PR directly to the [ionic-native repo](https://github.com/ionic-team/ionic-native) @armespavong?

**Comment by patiparnne** [comment]
FYI, for ionic 4, 5 please use [capacitor-navigation-bar](https://github.com/Jonarod/capacitor-navigation-bar) instead
