### ISSUE TITLE
Feature Request: Change the color of the navigation buttons

### ISSUE THREAD

**Issue by GoTo225** [armespavong/ionic-plugin-navigation-bar-color#2]
Hi @armespavong,
thank you for this truly amazing cordova plugin 👍

**Description**
During the usage of this plugin inside apps with light theme, I'm facing the issue that the appearance of the buttons inside the navigation bar cannot be modified. This leeds into hardly noticable navigation buttons, which can be seen below. In this example I've used the hex-color `#fff`.
![navigaton-bar-light-with-light-elements](https://user-images.githubusercontent.com/10572430/57568076-aafcad00-73e2-11e9-8823-a172ddc14bf9.png)

**Preferred Solution**
It would be nice to configure the button colors via predefined color schemes (like c[ordova-plugin-statusbar](https://github.com/apache/cordova-plugin-statusbar) with the `styleLightContent()` and `styleBlackTranslucent()` methods. With this solution the user can change the color, to guarantee a sufficient contrast between the nav buttons and the background:
![navigaton-bar-light-with-dark-elements](https://user-images.githubusercontent.com/10572430/57568122-4b52d180-73e3-11e9-919a-5e75a1151d15.png)

**Describe Alternatives**
Another possible way is to configure the nav button color via hex string.

**Comment by GoTo225** [comment]
Not relevant anymore, since The original Plugin provides already this feature

**Comment by zpbaldo** [comment]
Hi @GoTo225 , how did you solve it?

**Comment by GoTo225** [comment]
@zpbaldo I've used the [cordova plugin](https://github.com/armespavong/ionic-plugin-navigation-bar-color) directly without the typings of this library.
